// Auto-generated by scripts/generate-blur-data.mjs — do not edit manually
const BLUR_DATA: Record<string, string> = {
  'arashiyama': 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAoABUB8JQBOgBuKUH4NAAD+W6QgrlRwp7wNOmuDDdCkG+rm3KwwgAA=',
  'big-buddha': 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAoABUB8JYwCw7DZvQXFwAD+sK6k/kKgbx0ucaGk73vbX0sB8ezepO74AA==',
  'bund': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAoABUB8JagCdAEONMT4AP7i5P27jUr5feRD22KQTjKNhlu9cnrdgvNzmwwsAAA=',
  'dim-sum': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAoABUB8JQBOgCHeR0BqAAD+5GctWREnYuC3bsY/mX2sh8+Mp9KEZwMLVLIetOgAAA==',
  'dotonbori': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoKAAoABUB8JYwAAbohmsAAAP3FD727FMG2Mz075H0KxZF1wpbKCWNdR0AhwvufEgAAAA==',
  'forbidden-city': 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAoABUB8JZQCdADda1LIAADOPn3kR0wC5iSGHUh8E1xzLs33C68jDYc8bMmKODy0AAAA',
  'fushimi-inari': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAAoABUB8JbACdABf6tkAAP6oKNt4TSPyI1NW8YgO2femuvs+7klC1JeI9XdfVnxvzImvy/FqAAAA',
  'great-wall': 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAoABUB8JbACdAEVlJrGKAAA99+XUN+7/6ncERC3JG/RPCdh1KCCYBbDWnsHlf7IAAAA',
  'kinkakuji': 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoKAAoABUB8JYwC7ADZiZbAAP63CHHEVL01czFJFKGR0D5dfrXfPYzf0EyloM97ruAptzLHAeAAAA==',
  'kuromon-market': 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAoABUB8JQBOgCFq2wP7OAD+vJw3ej6AJnwEXqDZwNqOkcgXuq9J/wmfC7OVQAA=',
  'nanjing-road': 'data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAAoABUB8JYgCdAEe2AuznOAA/gTdJY9jJQ94T0nkCjRRWyHsmxBTPbWeaCAA',
  'night-market': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoKAAoABUB8JZACdADbRTQQ8uAAAN9J2P1ww72WThON2AmRbY2q/W5vQdNZJKqRtR1bld38I9C7QAAA',
  'osaka-castle': 'data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoKAAoABUB8JZQAAuY0u84YwAD+5xO0k7dWUqOz+3GA5y+gAAA=',
  'shanghai-skyline': 'data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAoABUB8JZAC7ADZi8mAAP5w8AuAP6oUSN2F26wZzZQGJycAAA==',
  'shibuya': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoKAAoABUB8JbACdADZsnnAAAD+6aVqV+R4p8a4XorZRWL1XnM+ybbJmNAXmZetyXESXuXYxiApgAAA',
  'shinsekai': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoKAAoABUB8JagC7ADYuCQAAMqmAAuQCRM9isus2VMVukwWlN0/84ljU4C+HD9VtK+cAA==',
  'star-ferry': 'data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAoABUB8JQBOgCHXfDYkIAD43n+fH1vrWkBbW5ykYY711svPRhmDaOTgAA==',
  'tea-ceremony': 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoKAAoABUB8JYwAAud9WKIAAP4/gHyjA3+rvVyUY6AcAQc5XZY50nWXIyp4Jv22udA06Wb9AjxJz0PgAAA=',
  'teamlab': 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoKAAoABUB8JbACdADcodqO0ADvsORdCeYnxN+sRMu9zAYVONQEkHuWeCvDdEjmsfLbY+rKXq2xboAA',
  'tsukiji': 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAAoABUB8JQBOgCKKbYSEmAAA/qobXSvOkLffP6Qdy/YRO1zo8c4dZRHTifU2UyobYGuzDkZAAA==',
  'victoria-peak': 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAoABUB8JYgCdADznzbuQADwMWsMKGsZhtTM1dA47oCFJ1o058CgPOWRKZyyPggAAA==',
  'yu-garden': 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAoABUB8JZQAAl1ouQ2AAP5AHCk0aSCr13FciJ4iNG9GhHTgkxAA',
};

/**
 * Returns a tiny base64 blur data URL for an itinerary image path.
 * Works with paths like "/images/itinerary/bund-800.webp".
 */
export function getBlurDataURL(imageUrl: string): string | undefined {
  const match = imageUrl.match(/^\/images\/itinerary\/(.+)-\d+\.webp$/);
  return match ? BLUR_DATA[match[1]] : undefined;
}
